apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eh994jv24-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a7b8175976.gig9.p3.openshiftapps.com/rhtap/rhtap-qe:53335b3b9fa329a008c8c724ec58a8e527127d6f@sha256:eb041a0c3ed4d29ffe26dbf7e5c3be825dc4e83ddce87bcf7391fc7049b2e53d
          name: container-image
